FROM node:18-alpine AS build-stage

# work derectory setting
WORKDIR /app

# copy package.json, package-lock.json
COPY package*.json ./

# install dependancy
RUN npm install

COPY . .
# Build it!
RUN npm run build 

FROM scratch AS export-stage
COPY --from=build-stage /app/dist /